### ISSUE TITLE
Cannot restore purchases.

### ISSUE THREAD

**Issue by JackStoneDev** [AlexDisler/ng-storekit#13]
I'm watching for a restore in two ways like so:

      $storeKit.watchPurchases()
      .then(function() {
      },
      function (error) {
      },
      function (purchase) {
        if (purchase.productId === "id")  {
          if (purchase.type === "restore") {
            alert("Restored.");
          }
        }
      },
      function(restore) {
        alert("Restored.");
      });

However, when I run `$storekit.restore()`, the first time I get nothing and then every time after that I get this message in the Xcode console:

`Ignoring restoreCompletedTransactionsWithApplicationUsername: because already restoring transactions`

What am I doing wrong? Thanks!

**Comment by sd031** [comment]
hi Jack I am getting the same issue , working hard to find solution of it from last two days , anyone can help ?
