### ISSUE TITLE
$storekit.restore does not work

### ISSUE THREAD

**Issue by marbetschar** [AlexDisler/ng-storekit#5]
How may I restore previously purchased items?
Executing $storekit.restore does not hay any effect - that said the appStoreOnPurchase method does not get fired :(

    $storekit.setLogging(true)
    $storekit.watchPurchases().then(appStoreOnSuccess,appStoreOnError,appStoreOnPurchase)
    $storekit.load([ ... ])
    $storekit.restore()

**Comment by w1zeman1p** [comment]
:+1:

**Comment by jeffleus** [comment]
Having the same problem.  None of the callbacks seem to be called after executing $storekit.restore().

appStoreOnSuccess - NO
appStoreOnError - NO
appStoreOnPurchase - NO

Any updates on this?
