### ISSUE TITLE
loadAppStoreReceipt() decoding appStoreReceipt()

### ISSUE THREAD

**Issue by jeffleus** [AlexDisler/ng-storekit#7]
I can't find much documentation on how to decode the appStoreReceipt that gets returned by loadAppStoreReceipt().  If I try to submit w/ the validateReceipt, I get an error 21002 that the JSON is malformed.  I have tried to take the string and use a base64 (utf-8) decoder, but most of what comes out is garbled.  I can see some blocks of test like the bundleid.  Anyone able to help on this?

**Comment by wimtar** [comment]
Having same issue. @jeffleus did you figure this guy out?

**Comment by jeffleus** [comment]
Sorry, just saw your question. I did get it working. But I don't remember off the top of my head what I did. Let me go back and look at the code and see if I can remember.

**Comment by jeffleus** [comment]
Here is a method that I put in a wrapper service that I think was working for me.  It does a loadAppStoreReceipt and then immediately uses this to run the validate.  I don't try to decode the receipt that i receive.  I haven't run or tested this in about 6-8mo, so YMM.

	function _checkAppReceipt() {
        var deferred = $q.defer();

		var isSandbox = true;
		$storekit.loadAppStoreReceipt().then(function(appStoreReceipt) {
			$storekit.validateReceipt(appStoreReceipt, isSandbox)
			.then(function(response) {
				deferred.resolve(response);
			})
			.catch(function(error) {
				deferred.reject(error);
			});
		});
		
		return deferred.promise;
	}
