### ISSUE TITLE
Bug: If purchase is canceled then purchased again, callbacks are never called.

### ISSUE THREAD

**Issue by wootwoot1234** [AlexDisler/ng-storekit#8]
To reproduce.  On an iOS device.  Begin a purchase and click cancel when it asks you to login.  Then begin the purchase again and either click cancel again or complete the purchase.  the purchase or error callback never get called on the second purchase attempt.

I think the promise status needs to be reset?  Maybe add ```deferred = $q.defer()``` to the ```watchPurchases``` callbacks?

**Comment by iamaro** [comment]
I'm experiencing this same issue. Did you ever figure out how to solve it? I'm not sure how to add the line you mentioned
